version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: taskmanager-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fullstack-app
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: taskmanager-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/fullstack-app
      - JWT_SECRET=your-production-jwt-secret-change-this
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: taskmanager-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
      - VITE_BASE_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongodb_data:
